---
# This playbook is an example for creating instances with volume.

# The play operates on the local (Ansible control) machine.
- name: Stage instance(s)
  hosts: local
  connection: local
  user: root
  gather_facts: false

  vars:
      keypair: philip
      instance_type: c3.4xlarge
      security_group: default
      image: ami-5978802e
      region: eu-west-1
      zone: eu-west-1c

  # Launch 1 instance with the following parameters.  Register the output.

  tasks:
    - name: Launch instance 
      ec2: keypair={{keypair}} group={{security_group}}
           instance_type={{instance_type}} image={{image}}
           wait=true count=1 region={{region}} zone={{zone}}
      register: ec2

    # Use the ec2_vol module to create volumes for attachment to each instance.
    # Use with_items to attach to each instance (by returned id) launched previously.

    - name: Create a volume and attach
      ec2_vol: volume_size=200 instance={{item.id}} region={{region}} zone={{zone}} 
      with_items: ec2.instances
      
    - name: Add tag to instances
      local_action: ec2_tag resource={{ item.id }} region={{region}} state=present
      with_items: ec2.instances
      args:
        tags:
          Name: Prod_TWS_Triggers1_5

      
