---
# Ansible playbook for an SVN2Git server.
#
# @author Jeff Geerling (2014).

- hosts: svn2git
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.svn
    - geerlingguy.git
    - geerlingguy.svn2git
