---
# Ansible playbook for an Apache Solr server.
#
# @author Jeff Geerling (2014).

- hosts: solr
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.java
    - geerlingguy.tomcat6
    - geerlingguy.solr
